### PR TITLE
Release1.2.0

### PR DESCRIPTION
**Pull request by baude**
* Reworked how netavark calls aardvark
* Implemented locking when committing
* Remove bridge only when no containers are attached
* Updated versions of libraries where possible

### CODE REVIEW

**Comment by baude** [comment]
anyone familiar with the regression here?

**Comment by Luap99** [comment]
Looks like some aardvark PR (most likely https://github.com/containers/aardvark-dns/pull/205) broke the test here.

**Comment by baude** [comment]
@flouthoc please fix

**Comment by flouthoc** [comment]
Following PR should fix this, could you please once this gets merged: https://github.com/containers/netavark/pull/419

**Pull request merged**
