### PR TITLE
README.md: remove latest release section

### PR DESCRIPTION
**Pull request by flouthoc**
Netavark follows github releases which is already listed on homepage. 
* Remove section which needs additional maintenance.
* Follow parity with other projects in github.com/containers such as podman.

Closes: https://github.com/containers/netavark/issues/440

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by baude** [comment]
lgtm

**Comment by mheon** [comment]
This is not a good idea. The Github release page is *strictly chronological*. If we ever have to do a, say, 1.0.2 release, that will appear as the latest release on Github - despite us already having 1.1.0 out. We retain and manually curate the latest release link on Podman because of this. Don't see a reason why NV and AV don't merit one?

**Comment by Luap99** [comment]
Well, the point is nobody seems to update it. So removing it sounds better to me than using the wrong version.

**Pull request merged**
