### PR TITLE
OWNERS: add cevich

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@flouthoc @baude @mheon @cevich @Luap99 PTAL

### CODE REVIEW

**Comment by lsm5** [comment]
is [CI:DOCS] keyword enabled here to skip CI for such changes?

**Review by flouthoc — APPROVED** [review]

**Comment by flouthoc** [comment]
LGTM

**Comment by cevich** [comment]
> is [CI:DOCS] keyword enabled here to skip CI for such changes?

It's not, and maybe not needed given how quickly the CI run takes?  If you/anyone *really* wants it, I can add it in, but it does make the yaml a bit confusing (use of "negative-logic" is required).

**Pull request merged**
