### PR TITLE
dns: double `fork` aardvark server to preserve its nature like a `daemon` although it will be killed by `podman`.

### PR DESCRIPTION
**Pull request by flouthoc**
* Its important that nature of aardvark server is more like a daemon
so following block ensures that aardvark server keeps on running even
if parent is killed

* `setsid()` ensures that there is no controlling terminal on the child process

### CODE REVIEW

**Comment by flouthoc** [comment]
This PR is not needed for `bats` as `bats` has a different issues. But we should still `double-fork` and keep using `--scope`.

**Comment by flouthoc** [comment]
I think we still need double forking as stated in the PR description.

cc @giuseppe for suggesting the idea of `setsid(` and `double-forking` due to the nature for aardvark as a long server.

**Review by giuseppe — APPROVED** [review]
LGTM

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by flouthoc** [comment]
I'm not sure how quickly I can add proper logging in a followup PR so to get it into working state I added @Luap99's patch

**Comment by flouthoc** [comment]
@Luap99 nvm I think we should I get `/dev/null` first I'll do some more testing add a loggin as well. Lets merge this later.

**Comment by Luap99** [comment]
This is no longer relevant

**Pull request closed without merging**
