### PR TITLE
core: spin `veth` pair on container namespace and move other end to host.

### PR DESCRIPTION
**Pull request by flouthoc**
Following PR makes sure that we create `veth` pair in container namespace
and move other end to host.

Reason: Prevent name collision of interfaces on host.

PR also improves meaning of error messages i.e if config specified `veth` pair already
exists on container namespace tell explicitly.

Closes: https://github.com/containers/netavark/issues/62

### CODE REVIEW

**Comment by flouthoc** [comment]
@Luap99 above PR should close linked issue. Feel free to try it out.

**Review by Luap99 — COMMENTED** [review]
LGTM
confirmed that this is working as expected

**Comment by baude** [comment]
LGTM

**Pull request merged**
