### PR TITLE
copr workaround: temporarily re-add .autocopr/netavark.spec

### PR DESCRIPTION
**Pull request by lsm5**
This should be gotten rid of once the copr infra upgrade to f35 is
complete

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@baude @mheon @Luap99 @rhatdan PTAL

### CODE REVIEW

**Comment by lsm5** [comment]
depends on https://github.com/containers/aardvark-dns/pull/25

**Comment by lsm5** [comment]
merge aardvark-dns PR first, then this one.

**Comment by flouthoc** [comment]
LGTM

**Comment by lsm5** [comment]
@baude @mheon @Luap99 could we merge this please?

**Comment by Luap99** [comment]
It looks like the CI is hanging, can you force-push

**Comment by lsm5** [comment]
@Luap99 @flouthoc good to go now.

**Pull request merged**
