### PR TITLE
Add rust container images

### PR DESCRIPTION
**Pull request by baude**
Add the build files for the rust container images to
contrib/container_images.  Build triggers will need to be done in quay
once this PR is commited.  From there, new container images for the rust
builds will be generated at each push to containers/netavark.

Signed-off-by: Brent Baude <bbaude@redhat.com>

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
Can you either delete the Readme or add content to it, otherwise LGTM

**Comment by Luap99** [comment]
Yeah me merged PRs without rebasing, https://github.com/containers/netavark/pull/342 will fix it

**Comment by baude** [comment]
when this merges, i will setup the trigger in quay to build.

**Pull request merged**
