### PR TITLE
run cargo update

### PR DESCRIPTION
**Pull request by Luap99**
Update deps with cargo update.

### CODE REVIEW

**Comment by Luap99** [comment]
@baude Can you rebuild the ubuntu20 image? The rust version is to old for the new deps. The current image has 1.57 but if you update it should have 1.59 which seems to work.

**Comment by baude** [comment]
LGTM

**Comment by Luap99** [comment]
@flouthoc @mheon PTAL

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm
/approve

**Pull request merged**
