### PR TITLE
[skip-ci] rpm: aardvark-dns is a hard dep across the board

### PR DESCRIPTION
**Pull request by lsm5**

### CODE REVIEW

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by lsm5** [comment]
@Luap99 ready for merge. thanks

**Comment by lsm5** [comment]
Did we enable merge pool for netavark? tide status says `in merge pool`.

**Comment by Luap99** [comment]
I think @cevich changes to actually enforce the merge protection on the Total Success task broke `[skip-ci]` as Total Success is not run here. @cevich can you fix this?

I guess for now I just merge manually.

**Pull request merged**
