### PR TITLE
Convert a few words to more inclusive ones

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
To make the code base more inclusive, I've changed a few variable names from "master*" to "primary*".

[NO NEW TESTS NEEDED]

Signed-off-by: tomsweeneyredhat <tsweeney@redhat.com>

### CODE REVIEW

**Review by Luap99 — CHANGES_REQUESTED** [review]
I disagree with this change, the correct name is master. That is how it is defined in the kernel netlink API. Renaming just makes it harder to understand the code IMO.

**Review by Luap99 — APPROVED** [review]
Based on internal discussion, LGTM

**Review by flouthoc — APPROVED** [review]
LGTM

**Pull request merged**
