### PR TITLE
Document how to generate a code coverage report for netavark

### PR DESCRIPTION
**Pull request by jakecorrenti**
Documents how to generate a code coverage report using coverage-profiling in the Rust compiler and the `grcov` tool created by Mozilla. Generates an HTML version of the report that you can open in the browser and navigate.

Current status:

image

### CODE REVIEW

**Comment by jakecorrenti** [comment]
@Luap99 PTAL

**Comment by jakecorrenti** [comment]
> LGTM

Running into issues with reproducibility. Sometimes a correct report is generated (in my case), but with the same packages @Luap99 hasn't been able to generate the same report. Looking into it

**Comment by jakecorrenti** [comment]
@Luap99 I made some super small changes, but I've been able to consistently reproduce a couple of times.

**Review by Luap99 — COMMENTED** [review]
Sorry I still only get the build.rs coverage.

**Comment by jakecorrenti** [comment]
The minor changes should be reproducible. Myself and Mohan were able to produce the same results.

**Comment by baude** [comment]
@jakecorrenti mind rebasing and see if we can get this across the finish line ?  re-running the tests didnt work.

**Comment by jakecorrenti** [comment]
looks like integration failed but integration_aarch64 is fine, maybe a restart would do the trick?

**Comment by mheon** [comment]
Tests now green.
/lgtm

**Pull request merged**
