### PR TITLE
Merge nv-dhcp-proxy into nv

### PR DESCRIPTION
**Pull request by baude**
The proxy is nearing completion and having them in separate repos has become problematic geiven that they both "use" each other.

### CODE REVIEW

**Comment by Luap99** [comment]
@baude @mheon @flouthoc @Jackbaude PTAL

**Comment by Jackbaude** [comment]
There are some outstanding PRs on the NV-dhcp-proxy that should be merged before we merge this in.

**Comment by baude** [comment]
> There are some outstanding PRs on the NV-dhcp-proxy that should be merged before we merge this in.

PRs should now be steered towards netavark.  I am going to deprecate the proxy repo.

**Comment by cevich** [comment]
> I assume I need to add the new binaries somewhere but I am not sure where.

I believe you need to touch `art_prep_script` in `.cirrus.yml to prevent the amd64 and arm64 binaries from name-clashing.

**Comment by cevich** [comment]
Re: [Build failure](https://cirrus-ci.com/task/4752069475696640) you can drop the 'netavark-dhcp-proxy.info' file rename, I don't think it's needed in this context.  Having the `netavark.info` file should be good enough for all binaries.

**Comment by Luap99** [comment]
Tests green, PTAL

**Comment by mheon** [comment]
LGTM

**Review by flouthoc — APPROVED** [review]
LGTM

**Pull request merged**
