### PR TITLE
Cirrus: Fix success failing on artifact extraction

### PR DESCRIPTION
**Pull request by cevich**
[There's a clash w/ the x86_64 binary `netavark-dhcp-proxy`](https://cirrus-ci.com/task/5061451941937152):

```
unzip armbinary.zip
+ unzip armbinary.zip
Archive:  armbinary.zip
replace bin/netavark-dhcp-proxy? [y]es, [n]o, [A]ll, [N]one, [r]ename:
NULL
(EOF or read error, treating as "[N]one" ...)
```

Rather than hard-code every new binary file, simply rename them all in a loop.

### CODE REVIEW

**Comment by Luap99** [comment]
netavark-dhcp-proxy no longer exists, why is this causing problems? https://github.com/containers/netavark/pull/619

Regardless not hard coding the names LGTM

**Comment by cevich** [comment]
> netavark-dhcp-proxy no longer exists

I can't find a good answer for that.  I searched all over in this PR's CI run and it's not built, stored or restored from any cache.

The example failing job was from 'main' on the 14th, and based on f3eaf86a1739e686fc7ce31af0c2e569863c3099.  The only explanation I have is [it was restored from cache.](https://cirrus-ci.com/task/4829640208941056?logs=bin#L2) before the build.  I can fix that by invalidating the cache key.

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by cevich** [comment]
I believe this PR is ready to go.

**Pull request merged**
