### PR TITLE
nftables/iptables: add dns rule for tcp as well

### PR DESCRIPTION
**Pull request by Luap99**

### CODE REVIEW

**Comment by mheon** [comment]
LGTM once this passes tests

**Comment by Luap99** [comment]
should we backport this into a 1.12.2?

**Comment by mheon** [comment]
Sounds like a good idea to me, we're loosely planning a Podman 5.2.2 anyways to get more Sigstore work landed so another NV (just NV? I don't think we need another AV) would not be out of the question.

**Comment by Luap99** [comment]
I found another issue that we leak container entries for aardvark-dns when we fail to start (i.e. port in use), now that netavark reports an error to podman the ctr is not started but the entries stay leaked.

I open another PR for that.

**Comment by Luap99** [comment]
@baude @flouthoc  PTAL

**Review by flouthoc — APPROVED** [review]
LGTM

**Pull request merged**
