### PR TITLE
NetworkOptions::load(): do not open /dev/stdin

### PR DESCRIPTION
**Pull request by Luap99**
There is no need to open /dev/stdin, we should just read directly from fd 0 without having to call open().

Also convert the error inside the function to prevent duplication.

### CODE REVIEW

**Comment by flouthoc** [comment]
Tests are failing with this PR

**Comment by mheon** [comment]
LGTM

**Comment by Luap99** [comment]
@baude @flouthoc PTAL

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm
/approve

**Pull request merged**
