### PR TITLE
Added a Requirement for podman 4.0+

### PR DESCRIPTION
**Pull request by afro-coder**
Hi, I've added a requirement for podman 4.0+ as many people are getting confused.

### CODE REVIEW

**Comment by mheon** [comment]
LGTM
@Luap99 @flouthoc @baude PTAL

**Comment by mheon** [comment]
Ah, wait, I think you forgot to push - the comment isn't addressed yet

**Comment by flouthoc** [comment]
Thanks for the PR.
LGTM once above comment is addressed.

**Review by flouthoc — CHANGES_REQUESTED** [review]
Thanks for the PR.
LGTM once above comment is addressed.

**Comment by afro-coder** [comment]
I tried to squash the commits but didn't work as intended I guess.

**Review by Luap99 — COMMENTED** [review]
LGTM

**Review by flouthoc — APPROVED** [review]
LGTM
/lgtm

**Pull request merged**
