### PR TITLE
Update serde_json and rand

### PR DESCRIPTION
**Pull request by baude**
Signed-off-by: Brent Baude <bbaude@redhat.com>

### CODE REVIEW

**Review by flouthoc — APPROVED** [review]
LGTM

**Comment by flouthoc** [comment]
@baude @mheon @Luap99 @lsm5 Should we have `podman` tests in this CI as well. Cause i believe there can be instances where vendoring changes passes `netavark` CI but it can cause hiccups with `podman`.

Although in this PR none of the `vendor` seems breaking to me. But some components like `netlink/tokio/iptables` in `netavark` and `tokio`,`trust-dns` in `aardvark`. They seem to pass `netavark/aardvark` CI but they can cause issues with `podman`.

**Comment by baude** [comment]
yes, we need to discuss this as a team however.

**Pull request merged**
