### PR TITLE
Add rpkg template for COPR autobuild

### PR DESCRIPTION
**Pull request by lsm5**
This commit removes .autocopr/netavark.spec in favor of
netavark.spec.rpkg to account for new recommendations for COPR builds.

https://lists.fedoraproject.org/archives/list/copr-devel@lists.fedorahosted.org/message/3JORYRKDWFMJSR35Z4LIKDEXH2T5263H/

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@baude @flouthoc @Luap99 @mheon @rhatdan PTAL . Similar to the change I did for podman

### CODE REVIEW

**Comment by lsm5** [comment]
added dependency on `aardvark-dns`. PTAL

**Comment by lsm5** [comment]
can we get eyes on this please?

**Review by flouthoc — APPROVED** [review]

**Comment by flouthoc** [comment]
LGTM

**Comment by lsm5** [comment]
i'm gonna remove the aardvark dependency for now until COPR is migrated to f35

**Comment by lsm5** [comment]
PTAL once again please

**Comment by flouthoc** [comment]
LGTM

**Pull request merged**
