### PR TITLE
cli: Integrate clap and bootstrap initial command structure.

### PR DESCRIPTION
**Pull request by flouthoc**
Adds initial command structure
```
netavark 0.0.1

USAGE:
    netavark [OPTIONS] <SUBCOMMAND>

FLAGS:
    -h, --help       Print help information
    -V, --version    Print version information

OPTIONS:
    -f, --file <FILE>    Instead of reading from STDIN, read the configuration to be applied from
                         the given file

SUBCOMMANDS:
    help        Print this message or the help of the given subcommand(s)
    setup       Configures the given network namespace with the given configuration
    teardown    Undo any configuration applied via setup command

```

### CODE REVIEW

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
This looks wrong
```
    -f, --file <FILE>    Instead of reading from STDIN, read the configuration to be applied from
                         the given file
``` 

Shouldn't this be for the subcommands not for the master command?

**Comment by rhatdan** [comment]
help        Print this message or the help of the given subcommand(s)
Why have a help subcommand, none of our tools do.

**Comment by rhatdan** [comment]
Why -V versus -v?  podman -v works?

**Comment by flouthoc** [comment]
@rhatdan `help` and `-V` comes directly from the library but i'll address these comments in a followup PR.

**Comment by flouthoc** [comment]
@rhatdan Idea for keeping `--file` with main was mainly  to avoid redundancy as it is common all subcommands. But can change this to keeping with individual subcommands. 
```
  -f, --file <FILE>    Instead of reading from STDIN, read the configuration to be applied from
                         the given file
```

**Comment by rhatdan** [comment]
Yes, put it in subcommands, just to future proof it.
I looked at the rust code and  indeed it seems like the CLI has builtin options.

**Comment by flouthoc** [comment]
Yeah they assign `-V` to version and leave `-v` intact as it is mostly kept reserved for `verbose` and `clap` is pretty much the most standard thing for rust. But i'll check if i can make it workaround.

**Comment by baude** [comment]
should there be a --debug or --verbose ?

**Comment by rhatdan** [comment]
@flouthoc don't worry about -v versus -V it is not a big deal and not worth fixing.  Same with help

**Pull request merged**
