### PR TITLE
[skip-ci] RPM: handle iptables/nftables dependencies

### PR DESCRIPTION
**Pull request by lsm5**
This was previously being handled in containers-common but is best handled here.

### CODE REVIEW

**Review by Luap99 — COMMENTED** [review]
Thanks, assuming this works this looks much cleaner now as we have one place where default_fw is defined.

**Comment by lsm5** [comment]
> Thanks, assuming this works this looks much cleaner now as we have one place where default_fw is defined.

Thanks, I can test this out before we merge.

**Comment by lsm5** [comment]
centos-stream-9
```
# dnf install netavark
Copr repo for podman-next owned by rhcontainerbot                                                                                                                                                                                                                                              7.8 MB/s | 2.7 MB     00:00    
Dependencies resolved.
===============================================================================================================================================================================================================================================================================================================================
 Package                                                        Architecture                                   Version                                                                                            Repository                                                                                              Size
===============================================================================================================================================================================================================================================================================================================================
Installing:
 netavark                                                       x86_64                                         102:1.11.0-1.20240725134611347444.pr1033.43.g74952f6.el9                                           copr:copr.fedorainfracloud.org:packit:containers-netavark-1033                                         3.5 M
Installing dependencies:
 aardvark-dns                                                   x86_64                                         102:1.11.0-1.20240723150024230707.main.26.gda4c52f.el9                                             copr:copr.fedorainfracloud.org:rhcontainerbot:podman-next                                              879 k
 iptables-libs                                                  x86_64                                         1.8.10-4.el9                                                                                       baseos                                                                                                 459 k
 iptables-nft                                                   x86_64                                         1.8.10-4.el9                                                                                       baseos                                                                                                 205 k
 libmnl                                                         x86_64                                         1.0.4-16.el9                                                                                       baseos                                                                                                  28 k
 libnetfilter_conntrack                                         x86_64                                         1.0.9-1.el9                                                                                        baseos                                                                                                  59 k
 libnfnetlink                                                   x86_64                                         1.0.1-21.el9                                                                                       baseos                                                                                                  30 k
 libnftnl                                                       x86_64                                         1.2.6-4.el9                                                                                        baseos                                                                                                  88 k

Transaction Summary

```

centos-stream-10
```
# dnf install netavark
Last metadata expiration check: 0:00:41 ago on Thu Jul 25 14:07:08 2024.
Dependencies resolved.
===============================================================================================================================================================================================================================================================================================================================
 Package                                                        Architecture                                   Version                                                                                            Repository                                                                                              Size
===============================================================================================================================================================================================================================================================================================================================
Installing:
 netavark                                                       x86_64                                         102:1.11.0-1.20240725134612306391.pr1033.43.g74952f6.el10                                          copr:copr.fedorainfracloud.org:packit:containers-netavark-1033                                         3.5 M
Installing dependencies:
 aardvark-dns                                                   x86_64                                         102:1.11.0-1.20240723150024230707.main.26.gda4c52f.el10                                            copr:copr.fedorainfracloud.org:rhcontainerbot:podman-next                                              901 k
 iptables-libs                                                  x86_64                                         1.8.10-8.el10                                                                                      baseos                                                                                                 450 k
 jansson                                                        x86_64                                         2.14-2.el10                                                                                        baseos                                                                                                  46 k
 libmnl                                                         x86_64                                         1.0.5-6.el10                                                                                       baseos                                                                                                  29 k
 libnetfilter_conntrack                                         x86_64                                         1.0.9-6.el10                                                                                       baseos                                                                                                  59 k
 libnfnetlink                                                   x86_64                                         1.0.1-28.el10                                                                                      baseos                                                                                                  30 k
 libnftnl                                                       x86_64                                         1.2.6-6.el10                                                                                       baseos                                                                                                  83 k
 nftables                                                       x86_64                                         1:1.0.9-4.el10                                                                                     baseos                                                                                                 416 k


```

**Comment by lsm5** [comment]
@jnovy @Luap99 PTAL.

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by lsm5** [comment]
@jnovy @Luap99 good for merge unless any further comments. Thanks.

**Review by Luap99 — APPROVED** [review]
/lgtm

**Pull request merged**
