### PR TITLE
COPR: fix build with git-core builddep

### PR DESCRIPTION
**Pull request by lsm5**
Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@Luap99 @flouthoc @baude @mheon PTAL.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by flouthoc** [comment]
@lsm5 Could you please open a PR to aardvark as well.

**Comment by lsm5** [comment]
@Luap99 @flouthoc yup, I will, soon as I get a successful build. It's failing on aardvark right now. Let me look a little further.

**Pull request merged**
