### PR TITLE
Cirrus: Update to newer CI VM images

### PR DESCRIPTION
**Pull request by cevich**

### CODE REVIEW

**Comment by Luap99** [comment]
Can you fix the lint issue or do you want me to take care of it?

**Comment by cevich** [comment]
@containers/netavark-maintainers PTAL.  I think a rust update in the VM [might be tripping up over some older code](https://cirrus-ci.com/task/6391573080965120).

**Comment by Luap99** [comment]
Well the error message is telling you what to change. But I can push this to the branch, no worries.

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by lsm5** [comment]
> @lsm5 What is up with the epel9 failure? Seems to be failing on all PRs.

@Luap99 I had to include epel9 for container-selinux gating tests. That env was missing the go-md2man dep which I have added now.

If there are any other failures, please run `slash-packit copr-build` to retrigger or do a rerun from the CI task list.

**Comment by cevich** [comment]
Thanks Lokesh

**Pull request merged**
