### PR TITLE
RPM: update .cargo/config before building

### PR DESCRIPTION
**Pull request by lsm5**

### CODE REVIEW

**Comment by lsm5** [comment]
@Luap99 @baude PTAL

**Comment by lsm5** [comment]
Let's get this in before #893

**Review by Luap99 — COMMENTED** [review]
https://github.com/containers/netavark/blob/main/DISTRO_PACKAGE.md#distro-packagers needs to be updated as well

I really hate that it includes the rev so we must update this every time we update the nftables dep which is ugly.

**Comment by lsm5** [comment]
> https://github.com/containers/netavark/blob/main/DISTRO_PACKAGE.md#distro-packagers needs to be updated as well
> 
> I really hate that it includes the rev so we must update this every time we update the nftables dep which is ugly.

done.

**Review by Luap99 — COMMENTED** [review]
LGTM

**Pull request merged**
